### PR TITLE
Added --aocalibrate option to srclist_by_beam.py

### PR DESCRIPTION
**Pull request by benjyman**
So I added in the option to output the sourcelist in Andre format. It shouldn't affect the normal use if you don't add in --aocalibrate!! If there is a shapelet in there it just skips it and gives out a warning.

### CODE REVIEW

**Comment by JLBLine** [comment]
Sounds good, happy ao calibrating!

**Comment by benjyman** [comment]
Woot! I feel like a real programmer =)
Now lets hope the whole EoR pipeline doesn't catch on fire...

**Comment by cjordan** [comment]
Hey lads, I've pulled these changes onto galaxy. Enjoy.

**Comment by JLBLine** [comment]
Whoa people using version control and keeping things up to date. This is
foreign to me and terrifying. Hopefully there has been no testing so at
least something normal is happening haha

**Pull request merged**
